### ISSUE TITLE
Error in IE11 even with Polyfill

### ISSUE THREAD

**Issue by Splode** [heavyy/vue-intersect#1]
First off, thanks for the plugin!

I have the Intersection Observer polyfill installed and am able to `console.log` the `IntersectionObserver` to confirm that it is working in IE11.

However, I receive the following error in IE11 when the `<intersect>` component would normally fire:
```
[Vue warn]: Error in event handler for "enter": "ReferenceError: 'SVGGraphicsElement' is undefined"

found in

---> <Intersect>
       <AppAbout> at src\components\About.vue
         <App> at src\App.vue
           <Root>
```

This error is only present in IE11.

Any clue as to what might be happening?

**Comment by tkjaergaard** [comment]
Hi Splode,

Thanks for reaching out, and I'm glad that you can use the Intersect component :)

the component SVGGraphicsElement is most properly in one of the child component of which you've wrapped the <Intersect> component.

Since SVGGraphicsElement does not exist either by reference or as a file in the repository: [see here](https://github.com/heavyy/vue-intersect/search?utf8=%E2%9C%93&q=SVGGraphicsElement&type=).

I think the error should be found some where within you project maybe?

It's difficult for me to say exactly what is going on. If your able to share some code with me i'll be happy to take a look to confidently say that it's not Vue-Intersect that is causing the error.

**Comment by Splode** [comment]
Hmm, that's strange. I'm not using SVGs in conjunction with any `vue-intersect` components. Here's where I have the first instance of `vue-intersect`:

```html
<intersect @enter.once="slideInLeft('about-img-01')">
      <div id="about-img-01" class="col-lg-5 col-md-8 mx-auto TopoBg ">
        <div class="Intrinsic-wrapper Intrinsic-wrapper--1x1 dotGrid dotGrid--gray dotGrid--touchstand">
          <img class="Intrinsic-item" :src="'./static/images/touchstand-01--1x1--505.jpg'" alt="Ideum multitouch table with motorized stand">
        </div>
      </div>
</intersect>
```

The `dotGrid` class has a background image (`.png`) associated with it:

```scss

.dotGrid--gray {
  &::before {
    background: url('../../../static/images/pat-dot--black--xparent--10.png');
  }
}
```

**Comment by tkjaergaard** [comment]
From the error you posted earlier is seems like the error is a reference error in the enter function, so perhaps "slideInLeft".

Could you share that?

**Comment by Splode** [comment]
Sure thing. I'm using the `popmotion` animation library. The workflow is:

1. Detect with `vue-intersect` if an HTML element has entered the viewport
2. Upon enter, fire `slideInLeft()` method, which selects aforementioned element by ID
3. Tween CSS properties using `popmotion`

```js
import { easing, tween, styler } from 'popmotion'

export default {
  methods: {
    slideInLeft (id) {
      const elStyler = styler(document.querySelector('#' + id))
      tween({
        from: { opacity: 0, x: -300 },
        to: { opacity: 1, x: 0 },
        duration: 1200,
        ease: easing.backOut
      }).start(elStyler.set)
    },

    slideInRight (id) {
      const elStyler = styler(document.querySelector('#' + id))
      tween({
        from: { opacity: 0, x: 300 },
        to: { opacity: 1, x: 0 },
        duration: 1200,
        ease: easing.backOut
      }).start(elStyler.set)
    }
  }
}
```

**Comment by tkjaergaard** [comment]
@Splode I'm sorry. But theres is nothing in that piece of code that gets me closer to an answer, unfortunately.

I really think that problem resist elsewhere in your application. Vue has what you could think of as a waterfall model with it's components. It goes from the top to the bottom. An error bubbles up the tree making it seems like that the error originates from the parent component while the error might actually originates for on ef the childs.

The error you are experiencing seems like your making an reference to an undefined variable. Somewhere you trying to access a variable called SVGGraphicsElement witch is undefined (ReferenceError).

Hope you find the bug, but I'm going to close this issue for now.

Happy coding 👾

**Comment by Splode** [comment]
Fair enough.

Thanks again.
