### ISSUE TITLE
@enter being called on leave

### ISSUE THREAD

**Issue by santicros** [heavyy/vue-intersect#20]
Hello,
My intersection @enter is also called when leaving the component. I don't know why. Just trying to test something  like this makes it call ENTER on enter and leave. 

`<intersect @enter="saySomething()"><h1>Hey</h1> </intersect>`

`methods: {
    saySomething() {
      console.log("ENTER");
    }
}`

I've tested in Firefox and Chrome and happens on both. And I'm using MacOS.

Thanks

**Comment by tkjaergaard** [comment]
Hi @santicros,

Could you make a CodeSandbox or replication of the issue?
