### ISSUE TITLE
Nuxt: unexpected identifier

### ISSUE THREAD

**Issue by MartinMalinda** [heavyy/vue-intersect#23]
<img width="678" alt="Screenshot 2020-06-30 at 14 43 45" src="https://user-images.githubusercontent.com/9468793/86127473-3a31bc00-bae0-11ea-8939-70910669dcb1.png">

`"vue-intersect": "^1.1.6",`
`"nuxt": "^2.12.2",`

I tried adding doing

```
build: {
    transpile: ['vue-intersect/dist/index'],
  },
```

But it doesn't seem to do the trick

**Comment by MartinMalinda** [comment]
dist seems to be out of sync:

https://github.com/heavyy/vue-intersect/blob/master/src/index.js#L29
https://github.com/heavyy/vue-intersect/blob/master/dist/index.js#L35

**Comment by MartinMalinda** [comment]
https://github.com/heavyy/vue-intersect/pull/24 does not seem to solve the issue

**Comment by MartinMalinda** [comment]
```
build: {
    transpile: ['vue-intersect'],
  },
```

works

**Comment by MentalGear** [comment]
Maybe add a "Nuxt install" section to the guide ?
