### ISSUE TITLE
Vue3 compatibility ?

### ISSUE THREAD

**Issue by HeyImNoxz** [heavyy/vue-intersect#28]
Hey, i tried to use your component in vue3 but its not compatible i think.

any plans for an update to support vue3 ?

**Comment by tkjaergaard** [comment]
Hi @HeyImNoxz,

Yeah! We definitely want to support Vue3 :) 

We've not started the development yet. But we will be :)

**Comment by tkjaergaard** [comment]
@HeyImNoxz use `npm i vue-intersect@next` to install Vue 3 version.
