### ISSUE TITLE
Nuxt: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by kgnfth** [heavyy/vue-intersect#29]
i get `Cannot use import statement outside a module` on first page load
but if a remove the intersect part from my component and save the file and refresh the page, then the page load fine

after that i add intersect back to my component and save it using HMR then the intersect works as expected until i refresh the page

from this issue #23 
i added transpile: ['vue-intersect'], to my build config but still the same error

version: `"vue-intersect": "^1.1.6",`

```vue
<template>
  <intersect @enter.once="onEnter">
    <div class="relative">
      <!-- Show the placeholder as background -->
      <blur-hash-img
        :hash="blurhash"
        :aspect-ratio="height / width"
        class="relative top-0 left-0 transition-opacity duration-500"
        :class="isLoaded ? 'opacity-0' : 'opacity-100'"
      />

      <!-- Show the real image on the top and fade in after loading -->
      <img
        ref="image"
        :width="width"
        :height="height"
        v-bind="$attrs"
        class="absolute top-0 left-0 w-full transition-opacity duration-500 cursor-pointer"
        :class="isLoaded ? 'opacity-100' : 'opacity-0'"
      />
    </div>
  </intersect>
</template>

<script>
import Intersect from 'vue-intersect'
export default {
  components: {
    Intersect,
  },
  inheritAttrs: false,
  props: {
    src: {
      type: String,
      required: true,
    },
    blurhash: {
      type: String,
      required: false,
      default: null,
    },
    width: {
      type: Number,
      default: 1,
    },
    height: {
      type: Number,
      default: 1,
    },
  },
  data() {
    return {
      isVisible: false,
      isLoaded: false,
    }
  },
  methods: {
    onEnter() {
      // Image is visible (means: has entered the viewport),
      // so start loading by setting the src attribute
      this.$refs.image.src = this.src
      this.$refs.image.onload = () => {
        // Image is loaded, so start fading in
        // is visible a little longer
        setTimeout(() => {
          this.isLoaded = true
        }, 500)
      }
    },
  },
}
</script>
```

**Comment by tkjaergaard** [comment]
Hi @kgnfth 😊

Do you use SSR?

Are you able to make a small repo that demonstrate the issue? 😊

**Comment by kgnfth** [comment]
> Hi @kgnfth 😊
> 
> Do you use SSR?
> 
> Are you able to make a small repo that demonstrate the issue? 😊

yes i use SSR

i will try to create a demo now

**Comment by tkjaergaard** [comment]
Cool, I’ve seen that issue with other modules when using SSR myself.

Happy to look at it when you have the demo ready 😊

**Comment by kgnfth** [comment]
@tkjaergaard pls see https://codesandbox.io/s/elated-colden-riqfw?file=/pages/index.vue

it works if u set `ssr` to `false`

**Comment by tkjaergaard** [comment]
Great, thank you 😊 
 I’ll give it a look and get back 😊

**Comment by tkjaergaard** [comment]
@kgnfth Okay, i looked into it, and i should perhaps state this out in the docs, but it's a Nuxt thing (or a SSR thing).

But you need to mark `vue-intersect` to be transpiled in order to work on the server part.

>nuxt.config.js
```
{
   ...
   build: {
     transpile: [
       /vue-intersect/
     ]
   }
}
```

Check out my fork of your CSB here: https://codesandbox.io/s/strange-driscoll-3l08f?file=/nuxt.config.js:872-905

**Comment by kgnfth** [comment]
@tkjaergaard yes it works. but not in my project, i think there is something wrong in my project which i have to dig in right now.

Thank you.
