### ISSUE TITLE
Trigger this automatically?

### ISSUE THREAD

**Issue by stephan-v** [heavyy/vue-intersect#5]
I have been looking for a component similar to this but being able to toggle a `v-if` automatically.

Currently it looks like this component still requires you to manually act opon the `@enter` event or `@leave` event and perform the logic that you want to perform.

`<intersect @enter="msg = 'Intersected'" @leave="msg = 'Not intersected'">`

Is there a way to automically toggle a `v-if` on the slot content without having to add extra markup?

**Comment by aaronransley** [comment]
@stephan-v DId you figure out a way to solve this?

**Comment by tkjaergaard** [comment]
I'm not sure what you're after? Is it to only apply the Intersect if some property isset?

If you could provide a basic example, then i might be able to replicate and write a test case.
